[pytest]
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*
markers =
    authentication: Маркировки для тестов, связанные с аутентификацией.
    regression: Маркировка для регрессионных тестов.